version: '3.7'
services:

  demo:
    container_name: backend-app
    build: app
    ports:
      - 8080:8080
    environment:
      restart: always
      POSTGRES_DB: demo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    depends_on:
      - postgres
    networks:
      - demonet

  postgres:
    container_name: pg_db
    image: postgres
    restart: always
    build: postgres
    expose:
      - '5432'
#    ports: #Use this instead of 'expose' to use Postgres container with real Spring app
#      - 5432:5432
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespass
    networks:
      - demonet

networks:
  demonet:
    driver: bridge