SET TIME ZONE 'UTC';

CREATE TABLE IF NOT EXISTS USR (
	ID          SERIAL        PRIMARY KEY,
	USERNAME    VARCHAR(50)   NOT NULL,
	EMAIL       VARCHAR(255)  NOT NULL,
	FIRST_NAME  VARCHAR(100)  NOT NULL,
	LAST_NAME   VARCHAR(100)  NOT NULL,
	PASSWORD    VARCHAR(255)  NOT NULL,
	CREATED     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	UPDATED     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	STATUS      VARCHAR(25)   DEFAULT 'ACTIVE',
	ENABLED     BOOLEAN       DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS ROLE (
	ID			SERIAL       NOT NULL PRIMARY KEY,
	NAME		VARCHAR(100) NOT NULL,
	CREATED TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	UPDATED TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	STATUS  VARCHAR(25)   NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS USR_ROLE (
	USER_ID INT NOT NULL,
	ROLE_ID INT NOT NULL,

	FOREIGN KEY (USER_ID) REFERENCES USR (ID),
	FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID),

	UNIQUE (USER_ID, ROLE_ID)
);

INSERT INTO USR (ID, USERNAME, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, ENABLED) VALUES (1, 'user', 'user@dom.com', 'test', 'user', '$2a$12$iegErWNO0iaavZmns5krpeOzetwDAA/0ETlhbBvVhuRtw1lfi8yW.', TRUE);
INSERT INTO ROLE (ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO USR_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);